### ISSUE TITLE
How make ent and casbin work together.

### ISSUE THREAD

**Issue by wahello** [casbin/ent-adapter#1]
#### How integrate [ent](https://github.com/ent/ent) with casbin?

**Comment by hsluoyz** [comment]
@closetool

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@hsluoyz almost done, but I encountered a bug https://github.com/ent/ent/issues/1552

**Comment by hsluoyz** [comment]
@wahello done and released: https://github.com/casbin/ent-adapter/releases/tag/v0.0.1
