### ISSUE TITLE
UpdateFilteredPolicies without match ptype when delete old rule with 0 fieldValues, so it will delete all policies

### ISSUE THREAD

**Issue by huijiezheng** [casbin/ent-adapter#16]
```
func (a *Adapter) UpdateFilteredPolicies(sec string, ptype string, newPolicies [][]string, fieldIndex int, fieldValues ...string) ([][]string, error) {
	oldPolicies := make([][]string, 0)
	err := a.WithTx(func(tx *ent.Tx) error {
		line := tx.CasbinRule.Query()
		if fieldIndex <= 0 && 0 < fieldIndex+len(fieldValues) {
			line = line.Where(casbinrule.V0EQ(fieldValues[0-fieldIndex]))
		}
		if fieldIndex <= 1 && 1 < fieldIndex+len(fieldValues) {
			line = line.Where(casbinrule.V1EQ(fieldValues[1-fieldIndex]))
		}
		if fieldIndex <= 2 && 2 < fieldIndex+len(fieldValues) {
			line = line.Where(casbinrule.V2EQ(fieldValues[2-fieldIndex]))
		}
		if fieldIndex <= 3 && 3 < fieldIndex+len(fieldValues) {
			line = line.Where(casbinrule.V3EQ(fieldValues[3-fieldIndex]))
		}
		if fieldIndex <= 4 && 4 < fieldIndex+len(fieldValues) {
			line = line.Where(casbinrule.V4EQ(fieldValues[4-fieldIndex]))
		}
		if fieldIndex <= 5 && 5 < fieldIndex+len(fieldValues) {
			line = line.Where(casbinrule.V5EQ(fieldValues[5-fieldIndex]))
		}
		rules, err := line.All(a.ctx)
		if err != nil {
			return err
		}
		for _, rule := range rules {
			if _, err := tx.CasbinRule.Delete().Where(
				casbinrule.IDEQ(rule.ID),
			).Exec(a.ctx); err != nil {
				return err
			}
		}
```

**Comment by huijiezheng** [comment]
And is it better to ignore the fieldValue when it's empty? Filtering with random field is more popular

**Comment by hsluoyz** [comment]
@JalinWang 

/cc @tangyang9464

**Comment by imp2002** [comment]
**verified**, I'll try fix it.

![image](https://user-images.githubusercontent.com/41513919/180751229-eaae1e1c-b454-49cc-8d81-89cdacad668b.png)

`e.UpdateFilteredPolicies([][]string{{"bob", "data2", "read"}}, 0, "bob", "data2")`

![image](https://user-images.githubusercontent.com/41513919/180751455-b6752bf5-199a-4363-9f36-66f9678a333d.png)

**Comment by imp2002** [comment]
Verified, I'll try fix it.

![image](https://user-images.githubusercontent.com/41513919/180752515-3a238a68-e0c5-4b9b-a2ef-da04797f9856.png)

`e.UpdateFilteredPolicies([][]string{{"bob", "data2", "read"}}, 0, "bob", "data2")`

![image](https://user-images.githubusercontent.com/41513919/180752634-35e7abec-bba4-48e1-bdfe-1e5ccda98409.png)

**Comment by JalinWang** [comment]
> And is it better to ignore the fieldValue when it's empty? Filtering with random field is more popular

It seems like the original code doesn't support empty filtering fields.
![image](https://user-images.githubusercontent.com/20621784/181917278-4f19aa75-64c1-44b7-86db-d75367ccf003.png)
![image](https://user-images.githubusercontent.com/20621784/181917349-9dc961f0-8880-47aa-9183-3ec84da57643.png)

Do we need to update other adapters like the below @tangyang9464 ?
https://github.com/casbin/ent-adapter/pull/17/files#diff-c5d420087ebe146b0024e82a914f630f79dc68b2f257bdfd9f0972eb584841b3R239
