### ISSUE TITLE
Proposal : Remove the active import of the go database package 

### ISSUE THREAD

**Issue by godcong** [casbin/ent-adapter#26]
```go
	_ "github.com/go-sql-driver/mysql"
	_ "github.com/jackc/pgx/v5/stdlib"
	_ "github.com/lib/pq"

	//_ "github.com/mattn/go-sqlite3"
```

Remove the active import of the go database package and let users import it themselves.
This eliminates the need to update the current library as third-party packages are updated.

**Comment by hsluoyz** [comment]
Didn't see many gains here
