### ISSUE TITLE
>go get github.com/casbin/ent-adapter  error

### ISSUE THREAD

**Issue by 957651480** [casbin/ent-adapter#7]
go: downloading github.com/casbin/ent-adapter v0.0.2
go: downloading github.com/jackc/pgx/v4 v4.11.0
go: downloading github.com/mattn/go-sqlite3 v1.14.6
go: downloading github.com/jackc/pgconn v1.8.1
go: downloading github.com/jackc/pgtype v1.7.0
go: downloading github.com/mattn/go-sqlite3 v1.14.7
# github.com/mattn/go-sqlite3
cgo: exec gcc: exec: "gcc": executable file not found in %PATH%

**Comment by hsluoyz** [comment]
@closetool
