### ISSUE TITLE
Seems not able to only load the filtered policies

### ISSUE THREAD

**Issue by vip30** [casbin/ent-adapter#9]
Is there able to get specific domain of policies in the database?
I think it is quite common that the table is getting bigger and will slow down the performance if getting everything from the database

There is similar feature implemented in gorm-adapter
https://github.com/casbin/gorm-adapter/blob/master/adapter.go#L434

Thanks!

**Comment by hsluoyz** [comment]
@closetool @tangyang9464 plz implement the FilteredAdapter interface.
